name: Bug report
description: Report a bug to help us improve
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      placeholder: What happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: 1. Go to ... 2. Click ... 3. See error
  - type: input
    id: env
    attributes:
      label: Environment
      placeholder: OS, Browser, Node version
  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots